CREATE SCHEMA `eurocoders_task_2`;

USE `eurocoders_task_2`;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE photos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  img VARCHAR(255) NOT NULL,
  date DATETIME,
  cat VARCHAR(45) NOT NULL,
  title VARCHAR(45) NOT NULL,
  uid INT NOT NULL,
  FOREIGN KEY (uid) REFERENCES users(id)
);

CREATE TABLE comments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  comment TEXT NOT NULL,
  date DATETIME,
  pid INT NOT NULL,
  FOREIGN KEY (pid) REFERENCES photos(id)
);